name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - '.github/workflows/*.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - '.github/workflows/*.yml'

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, macos, windows ]
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: ${{ runner.os }}-cargo-
    - run: just test
